/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Rozvrh_GUI;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author marti
 */
public class Rozvrh extends javax.swing.JFrame {

  

    /**
     * Creates new form Rozvrh
     */
    public Rozvrh() {
        initComponents();
        cviceni.removeAllItems();
        cviceni.disable();
        String[] predmety = {"ARCH", "PROM", "OS1", "ZUCET", "MAEK1"};
        predmet.setModel(new DefaultComboBoxModel(predmety));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        predmet = new javax.swing.JComboBox<>();
        pridat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        rozvrh = new javax.swing.JTable();
        cviceni = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        predmet.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        predmet.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                predmetItemStateChanged(evt);
            }
        });
        predmet.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                predmetFocusGained(evt);
            }
        });
        predmet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                predmetMouseClicked(evt);
            }
        });
        predmet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                predmetActionPerformed(evt);
            }
        });

        pridat.setText("Zapsaní");
        pridat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pridatMouseClicked(evt);
            }
        });

        rozvrh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Pondělí", null, null, null, null, null, null, null, null},
                {"Úterý", null, null, null, null, null, null, null, null},
                {"Středa", null, null, null, null, null, null, null, null},
                {"Čtvrtek", null, null, null, null, null, null, null, null},
                {"Pátek", null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "8:15 - 9:00", "9:05 - 9:50", "9:55 - 10:40", "10:45 - 11:30", "11:35 - 12:20", "12:25 - 13:10", "13:15 - 14:00", "14:05 - 14:50"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rozvrh.setAlignmentX(0.7F);
        rozvrh.setAlignmentY(0.7F);
        rozvrh.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(rozvrh);

        cviceni.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Vyberte předmět:");

        jLabel2.setText("Vyberte cvičení:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pridat, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1075, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cviceni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(predmet, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(predmet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cviceni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pridat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pridatMouseClicked
        // TODO add your handling code here:

        // <editor-fold defaultstate="collapsed" desc="ARCH">
        if (predmet.getSelectedItem().toString() == "ARCH") {
            rozvrh.setValueAt("ARCH - prednaska", 1, 1);
        } // </editor-fold>
        // <editor-fold defaultstate="collapsed" desc="PROM">
        else if ("PROM".equals(predmet.getSelectedItem().toString())) {
            rozvrh.setValueAt("PROM - prednaska", 1, 8);
            if (cviceni.getSelectedIndex() == 0) {
                rozvrh.setValueAt("PROM - cviceni", 0, 3);
                rozvrh.setValueAt("", 2, 6);
                rozvrh.setValueAt("", 2, 7);
            } else if (cviceni.getSelectedIndex() == 1) {
                rozvrh.setValueAt("PROM - cviceni", 2, 6);
                rozvrh.setValueAt("", 0, 3);
                rozvrh.setValueAt("", 2, 7);
            } else {
                rozvrh.setValueAt("PROM - cviceni", 2, 7);
                rozvrh.setValueAt("", 2, 6);
                rozvrh.setValueAt("", 0, 3);
            }

        } // </editor-fold>
        // <editor-fold defaultstate="collapsed" desc="ZUCET">
        else if ("ZUCET".equals(predmet.getSelectedItem().toString())) {
            rozvrh.setValueAt("ZUCET - prednaska", 0, 6);
            if (cviceni.getSelectedIndex() == 0) {
                rozvrh.setValueAt("ZUCET - cviceni", 1, 3);
                rozvrh.setValueAt("", 4, 7);
                rozvrh.setValueAt("", 2, 8);
            } else if (cviceni.getSelectedIndex() == 1) {
                rozvrh.setValueAt("ZUCET - cviceni", 4, 7);
                rozvrh.setValueAt("", 1, 3);
                rozvrh.setValueAt("", 2, 8);
            } else {
                rozvrh.setValueAt("ZUCET - cviceni", 2, 8);
                rozvrh.setValueAt("", 4, 7);
                rozvrh.setValueAt("", 1, 3);
            }

        } // </editor-fold>
        // <editor-fold defaultstate="collapsed" desc="OS1">
        else if ("OS1".equals(predmet.getSelectedItem().toString())) {
            rozvrh.setValueAt("OS1 - prednaska", 3, 2);
            if (cviceni.getSelectedIndex() == 0) {
                rozvrh.setValueAt("OS1 - cviceni", 0, 4);
                rozvrh.setValueAt("", 0, 5);

            } else if (cviceni.getSelectedIndex() == 1) {
                rozvrh.setValueAt("OS1 - cviceni", 0, 5);
                rozvrh.setValueAt("", 0, 4);

            }
        } // </editor-fold> 
        // <editor-fold defaultstate="collapsed" desc="MAEK1">
        else if ("MAEK1".equals(predmet.getSelectedItem().toString())) {
            rozvrh.setValueAt("MAEK1 - prednaska", 0, 2);
            if (cviceni.getSelectedIndex() == 0) {
                rozvrh.setValueAt("MAEK1 - cviceni", 1, 6);
                rozvrh.setValueAt("", 3, 6);
                rozvrh.setValueAt("", 4, 6);
            } else if (cviceni.getSelectedIndex() == 1) {
                rozvrh.setValueAt("MAEK1 - cviceni", 3, 6);
                rozvrh.setValueAt("", 1, 6);
                rozvrh.setValueAt("", 4, 6);
            } else {
                rozvrh.setValueAt("MAEK1 - cviceni", 4, 6);
                rozvrh.setValueAt("", 1, 6);
                rozvrh.setValueAt("", 3, 6);
            }

        }
        // </editor-fold>
    }//GEN-LAST:event_pridatMouseClicked

    private void predmetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_predmetActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_predmetActionPerformed

    private void predmetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_predmetMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_predmetMouseClicked

    private void predmetFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_predmetFocusGained
        // TODO add your handling code here: 

    }//GEN-LAST:event_predmetFocusGained

    private void predmetItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_predmetItemStateChanged
        // TODO add your handling code here: 
        String[] cviceniPROM = {"Po - 9:55 - 10:40", "St - 12:25 - 13:10", "St - 13:15 - 14:00"};
        String[] cviceniZUCET = {"Ut - 9:55 - 10:40", "Pa - 13:15 - 14:00", "St - 14:05 - 14:55",};
        String[] cviceniOS = {"Po - 10:45 - 11:30", "Po - 11:35 - 12:25"};
        String[] cviceniMAEK = {"Ut - 12:25 - 13:10", "Ct - 12:25 - 13:10", "Pa - 12:25 - 13:10"};
       // String [] bla = {.};
        if ("ARCH".equals(predmet.getSelectedItem().toString())) {
            cviceni.disable();
        }

        if ("PROM".equals(predmet.getSelectedItem().toString())) {
            cviceni.enable();
            cviceni.setModel(new DefaultComboBoxModel(cviceniPROM));
        }

        if ("ZUCET".equals(predmet.getSelectedItem().toString())) {
            cviceni.enable();
            cviceni.setModel(new DefaultComboBoxModel(cviceniZUCET));
        }

        if ("OS1".equals(predmet.getSelectedItem().toString())) {
            cviceni.enable();
            cviceni.setModel(new DefaultComboBoxModel(cviceniOS));
        }

        if ("MAEK1".equals(predmet.getSelectedItem().toString())) {
            cviceni.enable();
            cviceni.setModel(new DefaultComboBoxModel(cviceniMAEK));
        }
    }//GEN-LAST:event_predmetItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Rozvrh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Rozvrh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Rozvrh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Rozvrh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Rozvrh().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cviceni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> predmet;
    private javax.swing.JButton pridat;
    private javax.swing.JTable rozvrh;
    // End of variables declaration//GEN-END:variables
}
